apiVersion: apps/v1
kind: Deployment
metadata:
  name: newdep
spec:
  replicas: 10
  strategy:
    type: Recreate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      color: red
  template:
    metadata:
      labels:
        color: red
    spec:
      containers:
      - name: newdep-c1
        image: nginx
        ports:
        - containerPort: 80
