apiVersion: apps/v1
kind: Deployment
metadata:
  name: newdep
spec:
  replicas: 3
  selector:
    matchLabels:
      color: red
  template:
    metadata:
      labels:
        color: red
    spec:
      containers:
      - name: newdep-c1
        image: httpd
        ports:
        - containerPort: 80
