apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplica
spec:
  replicas: 3         #no. of pod
  selector:
    color: blue
  template: 
    metadata:
      name: myreplica
      labels:
        color: blue
    spec:
      containers:
        - name: myreplica
          image: httpd
          ports:
            - containerPort: 80
